---
- name: remove metrics components on {{ openshift_metrics_old_project }}
  command: >
    {{ openshift_client_binary }} -n {{ openshift_metrics_old_project }} --config={{ mktemp.stdout }}/admin.kubeconfig
    delete --ignore-not-found --selector=metrics-infra
    all,sa,secrets,templates,routes,pvc,rolebindings,clusterrolebindings,clusterrole
  register: delete_metrics
  changed_when: delete_metrics.stdout != 'No resources found'

- name: remove rolebindings on {{ openshift_metrics_old_project }}
  command: >
    {{ openshift_client_binary }} -n {{ openshift_metrics_old_project }} --config={{ mktemp.stdout }}/admin.kubeconfig
    delete --ignore-not-found
    rolebinding/hawkular-view
    clusterrolebinding/heapster-cluster-reader
    clusterrolebinding/hawkular-metrics
  changed_when: delete_metrics.stdout != 'No resources found'
